### ISSUE TITLE
Error parsing Guardian Defenders

### ISSUE THREAD

**Issue by KalChoedan** [Lokilicious/beautify#1]
**Describe the bug**
Unable to parse a list containing Guardian Defenders if the unit also contains a Heavy Weapons platform

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 65.0.1

**More Details**
Tested several variants of a simple list containing only Guardian Defenders.

If the list contains only Guardian Defenders, it imports fine.
If they have a Heavy Weapon platform, it fails to import.
It fails regardless of how many weapon platforms or which heavy weapon variant is selected.

**Please attach the HTML file you used when encountering the error**
(added .txt extension so Git would allow it to upload)
[test guardians + platform.html.txt](https://github.com/Lokilicious/beautify/files/2900531/test.guardians.%2B.platform.html.txt)

**Comment by Lokilicious** [comment]
Thanks, fixed already ;)
