### ISSUE TITLE
It would be nice if Stat values were centre aligned with the Stat names 

### ISSUE THREAD

**Issue by BaconCatBug** [Lokilicious/beautify#3]
They are on real datasheets and I think it would look a lot nicer. 
![untitled](https://user-images.githubusercontent.com/4897163/53363365-331afc80-3934-11e9-85e6-ff14298d89c6.png)
![untitled2](https://user-images.githubusercontent.com/4897163/53363369-34e4c000-3934-11e9-8d9e-119ede8d0919.png)

**Comment by Lokilicious** [comment]
Fixed :)
