### ISSUE TITLE
Drukhari Obsessions

### ISSUE THREAD

**Issue by Blank05** [Lokilicious/beautify#6]
**Describe the bug**
On my beautify document, only my Kabal obsessions shows. The Cult obsession doesn't.

**To Reproduce**
1.
4. 

**Expected behavior**
I expected the obsessions to populate.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Please attach the HTML file you used when encountering the error**

**Comment by Lokilicious** [comment]
Can you attach the HTML file? i could not reproduce the issue

**Comment by Blank05** [comment]
Sure.
