### ISSUE TITLE
"Something went wrong" message

### ISSUE THREAD

**Issue by xev74** [Lokilicious/beautify#8]
Hello,

Thanks for this very cool apps.

Since this morning, i have this message when uploading an HTML file from Battlescribe.

Something went wrong ...

No profile found, make sure to use full output

Reference ID: 2cdef3

Hint: Make sure to use "full" output, "minimal" output is not supported!

Hint 2: Make sure to export the HTML file, the Roster file is not supported!

**Comment by Lokilicious** [comment]
Hi, thanks for the issue, I could reproduce the issue with my internal tests... it seems there was a change to the BattleScribe format. I will try to fix it ASAP.

**Comment by Lokilicious** [comment]
Fixed
